[project]
name = "dbspec"
dynamic = ["version"]
requires-python = ">=3.11"
authors = [
  { name = "Jonny Bolton", email = "jonny.bolton16@gmail.com" },
]
description = "Simplifying SQL Server schema maintenance by utilising human-readable schema specifications"
readme = "README.md"

[project.optional-dependencies]
dev = [
  "pytest",
  "ruff",
]

[project.scripts]
dbspec = "dbspec.cli:main"

[build-system]
requires = [
  "setuptools>=80.9.0",
  "setuptools-scm[toml]>=8",
]
build-backend = "setuptools.build_meta"

[tool.ruff]
extend-exclude = ["src/dbspec/_version.py"]
line-length = 79
target-version = "py311"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "COM812", # trailing commas, use formatter instead
    "CPY001", # copyright notice, not required
    "ERA001", # commented-out code, useful when developing
    "FIX002", # todos, useful when developing
    "TD002",  # todo author, not required
    "TD003",  # todo link, not required
]

[tool.ruff.lint.isort]
force-sort-within-sections = true

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = [
  "INP001", # tests is not a package
  "S101",   # assertions, used by pytest
]

[tool.ruff.lint.pycodestyle]
max-doc-length = 72

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools_scm]
local_scheme = "no-local-version"
version_file = "src/dbspec/_version.py"
